### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by JonBoy1229** [johnnyq/pittpc_crm#108]
I use Dreamhost for hosting. I created the website (PHP 7.4) and a MySQL database, uploaded the files, go through the setup process. It takes the login page, but when I enter my credentials, it just reloads to the login page. I intentionally entered a wrong password and it gives me the incorrect credentials error then.

Any ideas?

**Comment by johnnyq** [comment]
Hi @JonBoy1229, it sounds like you did everything right. Lets see if we can break this down to see what may be going on.

- Verify config.php has been created?
- Verify that the initial user got created and there is a record of that user under users tables in phpmyadmin?
- Copy and paste snippets of your error log (php, apache, nginx)

**Comment by JonBoy1229** [comment]
Hi Johnny,
Config.php is created. I even deleted it and created a new MySQL DB to make sure I didn't screw something up and it regenerated with the new DB info in it.

User account shows up on the Users table of the DB.

The host I'm using is a shared webhost, so I'm honestly not sure how to get those logs. I mainly use the host to run some base Wordpress sites.

**Comment by johnnyq** [comment]
The logs will probably be our biggest help sometime the logs will be in the directory called logs or sometimes they may be on the web control panel itself. I'm not entirely familiar with Dreamhost. I could take a quick look tonight if you PM me info to login, but lets see if we can track down the logs first that will be most helpful.

**Comment by johnnyq** [comment]
@JonBoy1229 I'm going to close this issue for now as i'm unable to replicate it please report back if you are still having the issue. Thanks
