### ISSUE TITLE
Can't login - login page redirects to itself

### ISSUE THREAD

**Issue by nicktimmermans84** [johnnyq/pittpc_crm#114]
After attempting to login, the login page refreshes. Not able to get to dashboard.

**Comment by johnnyq** [comment]
I'm just taking a guess here but out of all the things It could possibly be a web browser issue, try with a fresh install of chrome or Firefox and report back extension free.

**Comment by johnnyq** [comment]
I'm going to mark this resolved as i am not able to replicate and have not recieved a response. You are welcome to open a new issue if there are further issues.
