### ISSUE TITLE
Give this project a name

### ISSUE THREAD

**Issue by johnnyq** [johnnyq/pittpc_crm#51]
This project really needs a name

**Comment by TimelesslyPrecise** [comment]
MyITManager_CE

MyProMSP_CE

MyITCrm_CE

Trust_IT_Invoicing

ITFrontOffice

MSPFrontOffice

Smile_IT_Accounting

Clarity_IT_Accounting

Clarity_CRM

Clarity_MSP_Assistant

Clarity_IT_Assistant

Skill Assistant

Joy Invoicing

![kermitpopcorn](https://user-images.githubusercontent.com/39248682/64912334-a97a2300-d6fb-11e9-90e3-ce053b5ada3c.PNG)

**Comment by johnnyq** [comment]
We have concluded the name will be ITFlow
