### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by Cr0ssix** [johnnyq/pittpc_crm#96]
Hello, i upload this to my webserver, created the db and fill out all the information, after click on save it comes back to the install and then its taking me to the same process (loop) where have to fill out all over again? do am i missing something?

**Comment by Cr0ssix** [comment]
Hello?

**Comment by johnnyq** [comment]
@Cr0ssix this should be fixed, give it another go and let us know

**Comment by johnnyq** [comment]
closing it appears to be fixed
